<style>
.icon-size {
    font-size:60px;
}

.shoppingBadge-custom{
    background: red;
    position:absolute;
    left:47px; /** you can make changes here to change position **/
    top:18px;
    font-size:14px;
    z-index: 3;
}
</style>
  <link rel="stylesheet" href="bootstrap/dist/css/bootstrap.css">    
  <link href="https://fonts.googleapis.com/css?family=Caveat|Knewave" rel="stylesheet">
<div class="container">
    <i class="glyphicon glyphicon-calendar icon-size"></i>
    <span class="badge shoppingBadge shoppingBadge-custom">TUTUTUTUT</span>
</div>